# Set variable from env.sh

SET (LEIOT_ENV_PATH $ENV{PATH})
SET (LEIOT_CROSS_PREFIX $ENV{CROSS_PREFIX})
SET (LEIOT_ENABLE_DEBUG $ENV{ENABLE_DEBUG})
SET (LEIOT_OS_PLATFORM $ENV{OS_PLATFORM})
SET (LEIOT_DEVICE_TYPE $ENV{DEVICE_TYPE})
SET (LEIOT_LIBS_STATIC $ENV{ENABLE_STATIC})

# Check env
IF (NOT LEIOT_DEVICE_TYPE)
    MESSAGE (FATAL_ERROR "Please specify the device type!")
ENDIF ()

IF (NOT LEIOT_OS_PLATFORM)
    MESSAGE (FATAL_ERROR "Please specify the os platform!")
ENDIF ()

# Display on ccmake
SET (LEIOT_CROSS_PREFIX ${LEIOT_CROSS_PREFIX} CACHE STRING "RO Compiler prefix")
SET (LEIOT_OS_PLATFORM ${LEIOT_OS_PLATFORM} CACHE STRING "RO OS Platform")
SET (LEIOT_DEVICE_TYPE ${LEIOT_DEVICE_TYPE} CACHE STRING "RO Device type")

# Console show env info
MESSAGE (STATUS "ENV LEIOT_CROSS_PREFIX: ${LEIOT_CROSS_PREFIX}")
MESSAGE (STATUS "ENV LEIOT_ENABLE_DEBUG: ${LEIOT_ENABLE_DEBUG}")
MESSAGE (STATUS "ENV LEIOT_ENABLE_STATIC: ${LEIOT_ENABLE_STATIC}")
MESSAGE (STATUS "ENV LEIOT_OS_PLATFORM: ${LEIOT_OS_PLATFORM}")
MESSAGE (STATUS "ENV LEIOT_DEVICE_TYPE: ${LEIOT_DEVICE_TYPE}")
